spring.application.name=cadastro-usuario
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.datasource.url=jdbc:h2:mem:usuarios
spring.h2.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

server.port = 8081



